CREATE DATABASE QLDUNGCULAMBANH
GO
USE QLDUNGCULAMBANH
GO
CREATE TABLE POSITION(
id       	INT NOT NULL PRIMARY KEY IDENTITY(1,1),
Name		VARCHAR(128) NOT NULL)
GO
CREATE TABLE ACCOUNT(
id       	INT NOT NULL PRIMARY KEY IDENTITY(1,1),
UserName 	VARCHAR(128) NOT NULL,
Password 	VARCHAR(128) NOT NULL,
Status   	CHAR(1) NULL,
PositionId 	INT FOREIGN KEY REFERENCES POSITION(id))
GO
CREATE TABLE ADMIN(
id       	INT NOT NULL PRIMARY KEY IDENTITY(1,1),
FirstName	VARCHAR(128) NOT NULL,
LastName	VARCHAR(128) NOT NULL,
UserName	VARCHAR(128) NOT NULL,
AccountId	INT FOREIGN KEY REFERENCES ACCOUNT(id))
GO
CREATE TABLE CUSTOMER(
id       	INT NOT NULL PRIMARY KEY IDENTITY(1,1),
FirstName	VARCHAR(128) NOT NULL,
LastName	VARCHAR(128) NOT NULL,
Birth		DATE NULL,
Gender		CHAR(1) NULL,
Email		VARCHAR(128) NULL,
Phone		VARCHAR(128) NULL,
Address		NVARCHAR(500) NULL,
AccountId	INT FOREIGN KEY REFERENCES ACCOUNT(id))
GO
CREATE TABLE BILL(
id       	INT NOT NULL PRIMARY KEY IDENTITY(1,1),
Status		CHAR(1) NULL,
Note		NVARCHAR(500) NULL,
CreatedBy	VARCHAR(128) NULL,
CreatedDate	DATETIME NULL,
ModifiedBy	VARCHAR(128) NULL,
ModifiedDate	DATETIME NULL,
Isdeleted	BIT NULL,
CustomerId	INT FOREIGN KEY REFERENCES CUSTOMER(id),
AdminId		INT FOREIGN KEY REFERENCES ADMIN(id))
GO
CREATE TABLE CATEGORY(
id       	INT NOT NULL PRIMARY KEY IDENTITY(1,1),
Name		NVARCHAR(150) NOT NULL,
Status		CHAR(1) NULL,
CreatedBy	VARCHAR(128) NULL,
CreatedDate	DATETIME NULL,
ModifiedBy	VARCHAR(128) NULL,
ModifiedDate	DATETIME NULL,
Isdeleted	BIT NULL)
GO
CREATE TABLE PRODUCT(
id       		INT NOT NULL PRIMARY KEY IDENTITY(1,1),
Name			NVARCHAR(150) NOT NULL,
Price			DECIMAL NULL,
ShortDescription	NVARCHAR(500) NOT NULL,
Description		NVARCHAR(500) NOT NULL,
Quantity		INT NULL,
Status			CHAR(1) NULL,
CreatedBy		VARCHAR(128) NULL,
CreatedDate		DATETIME NULL,
ModifiedBy		VARCHAR(128) NULL,
ModifiedDate		DATETIME NULL,
Isdeleted		BIT NULL,
CategoryId		INT FOREIGN KEY REFERENCES CATEGORY(id))
GO
CREATE TABLE PRODUCT_PICTURE(
id       	INT NOT NULL PRIMARY KEY IDENTITY(1,1),
Name		NVARCHAR(150) NOT NULL,
Picture		NVARCHAR(150) NOT NULL,
Status		CHAR(1) NULL,
CreatedBy	VARCHAR(128) NULL,
CreatedDate	DATETIME NULL,
ModifiedBy	VARCHAR(128) NULL,
ModifiedDate	DATETIME NULL,
Isdeleted	BIT NULL,
ProductId	INT FOREIGN KEY REFERENCES PRODUCT(id))
GO
CREATE TABLE BILL_DETAILS(
id       	INT NOT NULL PRIMARY KEY IDENTITY(1,1),
Quantity	INT NULL,
CreatedBy	VARCHAR(128) NULL,
CreatedDate	DATETIME NULL,
BillId		INT FOREIGN KEY REFERENCES BILL(id),
ProductId	INT FOREIGN KEY REFERENCES PRODUCT(id))
GO
CREATE TABLE RETURNS(
id       	INT NOT NULL PRIMARY KEY IDENTITY(1,1),
Reason		NVARCHAR(150) NOT NULL,
Status		CHAR(1) NULL,
CreatedBy	VARCHAR(128) NULL,
CreatedDate	DATETIME NULL,
BillId		INT FOREIGN KEY REFERENCES BILL(id))
GO
CREATE TABLE RETURNS_DETAILS(
id       	INT NOT NULL PRIMARY KEY IDENTITY(1,1),
Price		DECIMAL NULL,
Quantity	INT NULL,
ReturnsId	INT FOREIGN KEY REFERENCES RETURNS(id),
ProductId	INT FOREIGN KEY REFERENCES PRODUCT(id))
GO
CREATE TABLE SUPPLIER(
id       	INT NOT NULL PRIMARY KEY IDENTITY(1,1),
Name		NVARCHAR(150) NOT NULL)
GO
CREATE TABLE IMPORT_COUPON(
id       	INT NOT NULL PRIMARY KEY IDENTITY(1,1),
Status		CHAR(1) NULL,
Note		NVARCHAR(500) NOT NULL,
CreatedBy	VARCHAR(128) NULL,
CreatedDate	DATETIME NULL,
ModifiedBy	VARCHAR(128) NULL,
ModifiedDate	DATETIME NULL,
Isdeleted	BIT NULL,
SupplierId	INT FOREIGN KEY REFERENCES SUPPLIER(id),
ProductId	INT FOREIGN KEY REFERENCES PRODUCT(id),	
AdminId		INT FOREIGN KEY REFERENCES ADMIN(id))
GO
CREATE TABLE IMPORT_COUPON_DETAILS(
id       	INT NOT NULL PRIMARY KEY IDENTITY(1,1),
Price		DECIMAL NULL,
Quantity	INT NULL,
CreatedBy	VARCHAR(128) NULL,
CreatedDate	DATETIME NULL,
ImportCouponId	INT FOREIGN KEY REFERENCES IMPORT_COUPON(id))
GO
CREATE TABLE POSTS(
id       	INT NOT NULL PRIMARY KEY IDENTITY(1,1),
Title		VARCHAR(500) NULL,
SupTitle	VARCHAR(500) NULL,
Content		VARCHAR(500) NULL,
ViewCount	VARCHAR(500) NULL,
Status		CHAR(1) NULL)
GO
CREATE TABLE BANNER_TIER(
id       	INT NOT NULL PRIMARY KEY IDENTITY(1,1),
Banner_top	VARCHAR(500) NULL,
Banner_bottom	VARCHAR(500) NULL,
Banner_left	VARCHAR(500) NULL,
Banner_right	VARCHAR(500) NULL,
Status		CHAR(1) NULL)
GO
CREATE TABLE BANNER_PICTURE(
id       	INT NOT NULL PRIMARY KEY IDENTITY(1,1),
Name		VARCHAR(500) NULL,
Picture		VARCHAR(500) NULL,
BannerTierId	INT FOREIGN KEY REFERENCES BANNER_TIER(id))























